name: Publish single image

on:
  workflow_call:
    inputs:
      ps-version:
        required: true
        type: string
      php-version:
        required: true
        type: string
      webserver:
        required: true
        type: string
      platforms:
        required: true
        type: string
    # secrets:
    #   DOCKERHUB_USERNAME:
    #     required: true
    #   DOCKERHUB_TOKEN:
    #     required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the images from Dockerfile
      - name: Build and push the Docker image
        run: docker buildx build --push --file Dockerfile --platform ${{ inputs.platforms }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/prestashop:${{ inputs.ps-version }}-${{ inputs.php-version }}-${{ inputs.webserver }} --build-arg PHP_VERSION=${{ inputs.php-version }} --build-arg PS_VERSION=${{ inputs.ps-version }} --build-arg WEB_SERVER=${{ inputs.webserver }} .
